/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import clases.conexion;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author mateo
 */
public class frmRegistro extends javax.swing.JFrame {

    public static int avatar = 0;
    public static String nombre = "";

    public frmRegistro() {
        initComponents();
        setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(lblFondo, "src/imagenes/fondoSU.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblBack, "src/imagenes/back.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblAvatar, "src/imagenes/pregunta.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblAbierto, "src/imagenes/desbloquear.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblCerrado, "src/imagenes/bloquear.png");
        lblCerrado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUs = new javax.swing.JTextField();
        txtEdadMas = new javax.swing.JTextField();
        txtMascota = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        txtConfirmar = new javax.swing.JPasswordField();
        cbxSexo = new javax.swing.JComboBox<>();
        lblAvatar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxAvatar = new javax.swing.JComboBox<>();
        lblAbierto = new javax.swing.JLabel();
        lblCerrado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Información de usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Contraseña:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Confirmar:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Edad Mascota");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Mascota:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Sexo mascota");

        txtUs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtEdadMas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtMascota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        cbxSexo.setBackground(new java.awt.Color(153, 0, 51));
        cbxSexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Masculino", "Femenino", " " }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Eliga su avatar:");

        cbxAvatar.setBackground(new java.awt.Color(0, 102, 51));
        cbxAvatar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxAvatar.setForeground(new java.awt.Color(255, 255, 255));
        cbxAvatar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Avatar1", "Avatar2", "Avatar3", "Avatar4", "Avatar5", "Avatar6", "Avatar7", "Avatar8" }));
        cbxAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxAvatarMouseClicked(evt);
            }
        });
        cbxAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAvatarActionPerformed(evt);
            }
        });

        lblAbierto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAbiertoMouseClicked(evt);
            }
        });

        lblCerrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerradoMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUs, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(2, 2, 2)
                                        .addComponent(txtEdadMas, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(37, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(361, 361, 361))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(404, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdadMas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cbxAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 840, 580));
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        frmInicioSeccion obj1 = new frmInicioSeccion();
        obj1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblAbiertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAbiertoMouseClicked
        txtPass.setEchoChar((char) 0);
        txtConfirmar.setEchoChar((char) 0);
        lblAbierto.setVisible(false);
        lblCerrado.setVisible(true);
    }//GEN-LAST:event_lblAbiertoMouseClicked

    private void lblCerradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerradoMouseClicked
        txtPass.setEchoChar('*');
        txtConfirmar.setEchoChar('*');
        lblAbierto.setVisible(true);
        lblCerrado.setVisible(false);
    }//GEN-LAST:event_lblCerradoMouseClicked

    private void cbxAvatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxAvatarMouseClicked

    }//GEN-LAST:event_cbxAvatarMouseClicked

    private void cbxAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAvatarActionPerformed
        if (cbxAvatar.getSelectedItem().toString().equals("Avatar1")) {
            rsscalelabel.RSScaleLabel.setScaleLabel(lblAvatar, "src/avatar/calvo.png");
            avatar = 1;
        }
        if (cbxAvatar.getSelectedItem().toString() == "Avatar2") {
            rsscalelabel.RSScaleLabel.setScaleLabel(lblAvatar, "src/avatar/facha.png");
            avatar = 2;
        }
        if (cbxAvatar.getSelectedItem().toString() == "Avatar3") {
            rsscalelabel.RSScaleLabel.setScaleLabel(lblAvatar, "src/avatar/jefa.png");
            avatar = 3;
        }
        if (cbxAvatar.getSelectedItem().toString() == "Avatar4") {
            rsscalelabel.RSScaleLabel.setScaleLabel(lblAvatar, "src/avatar/kevin.png");
            avatar = 4;
        }
        if (cbxAvatar.getSelectedItem().toString() == "Avatar5") {
            rsscalelabel.RSScaleLabel.setScaleLabel(lblAvatar, "src/avatar/lentes.png");
            avatar = 5;
        }
        if (cbxAvatar.getSelectedItem().toString() == "Avatar6") {
            rsscalelabel.RSScaleLabel.setScaleLabel(lblAvatar, "src/avatar/mujer.png");
            avatar = 6;
        }
        if (cbxAvatar.getSelectedItem().toString() == "Avatar7") {
            rsscalelabel.RSScaleLabel.setScaleLabel(lblAvatar, "src/avatar/negra.png");
            avatar = 7;
        }
        if (cbxAvatar.getSelectedItem().toString() == "Avatar8") {
            rsscalelabel.RSScaleLabel.setScaleLabel(lblAvatar, "src/avatar/rubia.png");
            avatar = 8;
        }
    }//GEN-LAST:event_cbxAvatarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nombre = txtNombre.getText();

        try {
            String usuario, contraseña, nombreM, nombreU, confirmar;
            int edad, avatar=0, sexo=0;
            int longitud1;
            int longitud2;
            int longitud3;
            int longitud4;
            int longitud5;
            usuario = txtUs.getText();
            contraseña = txtPass.getText();
            nombreM = txtMascota.getText();
            nombreU = txtNombre.getText();
            confirmar = txtConfirmar.getText();
            if (txtUs.getText().equals("") && txtPass.getText().equals("") && txtConfirmar.getText().equals("") && txtEdadMas.getText().equals("") && txtMascota.getText().equals("") && txtNombre.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Llene todos los campos");
            } else if (txtUs.getText().equals("") || txtPass.getText().equals("") || txtConfirmar.getText().equals("") || txtEdadMas.getText().equals("") || txtMascota.getText().equals("") || txtNombre.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Llene todos los campos");
            } else {
                if (!txtPass.getText().equals(txtConfirmar.getText())) {
                    JOptionPane.showMessageDialog(null, "Contraseñas no coinciden");
                } else if (cbxAvatar.getSelectedItem().toString().equals("Seleccione:") && cbxSexo.getSelectedItem().toString().equals("Seleccione:")) {
                    JOptionPane.showMessageDialog(null, "Seleccione una opcion");
                } else if (cbxAvatar.getSelectedItem().toString().equals("Seleccione:") || cbxSexo.getSelectedItem().toString().equals("Seleccione:")) {
                    JOptionPane.showMessageDialog(null, "Seleccione una opcion");
                } else {
                    if (cbxAvatar.getSelectedItem().toString().equals("Avatar1")) {
                        avatar=1;
                    }
                    if (cbxAvatar.getSelectedItem().toString().equals("Avatar2")) {
                        avatar=2;
                    }
                    if (cbxAvatar.getSelectedItem().toString().equals("Avatar3")) {
                        avatar=3;
                    }
                    if (cbxAvatar.getSelectedItem().toString().equals("Avatar4")) {
                        avatar=4;
                    }
                    if (cbxAvatar.getSelectedItem().toString().equals("Avatar5")) {
                        avatar=5;
                    }
                    if (cbxAvatar.getSelectedItem().toString().equals("Avatar6")) {
                        avatar=6;
                    }
                    if (cbxAvatar.getSelectedItem().toString().equals("Avatar7")) {
                        avatar=7;
                    }
                    if (cbxAvatar.getSelectedItem().toString().equals("Avatar8")) {
                        avatar=8;
                    }
                    
                    if (cbxSexo.getSelectedItem().toString().equals("Masculino")) {
                        sexo=1;
                    }if (cbxSexo.getSelectedItem().toString().equals("Femenino")) {
                        sexo=0;
                    }
                   longitud1 =usuario.length();
                   longitud2 =contraseña.length();
                   longitud3 =confirmar.length();
                   longitud4 =nombreM.length();
                   longitud5 =nombreU.length();
                    if (longitud1>=20) {
                        JOptionPane.showMessageDialog(null,"Todos los campos\nsolo permiten hasta\n20 caracteres");
                    }else if (longitud2>=20) {
                        JOptionPane.showMessageDialog(null,"Todos los campos\nsolo permiten hasta\n20 caracteres");
                    }else if (longitud3>=20) {
                        JOptionPane.showMessageDialog(null,"Todos los campos\nsolo permiten hasta\n20 caracteres");
                    }else if (longitud4>=20) {
                        JOptionPane.showMessageDialog(null,"Todos los campos\nsolo permiten hasta\n20 caracteres");
                    }else if (longitud5>=20) {
                        JOptionPane.showMessageDialog(null,"Todos los campos\nsolo permiten hasta\n20 caracteres");
                    }else{
                        edad = Integer.parseInt(txtEdadMas.getText());
                        conexion.RegistroUsuario(usuario,contraseña,edad,nombreU,sexo,avatar,nombreM);
                        JOptionPane.showMessageDialog(null,"Bienvendo "+nombreU);
                        frmCita.InicioSeccio=1;
                        frmPrincipal obj1 = new frmPrincipal();
                        obj1.setVisible(true);
                        this.setVisible(false);
                    }
                }
            }
            
            
            
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Llene bien los campos");
            txtEdadMas.setBackground(Color.red);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxAvatar;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAbierto;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCerrado;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPasswordField txtConfirmar;
    private javax.swing.JTextField txtEdadMas;
    private javax.swing.JTextField txtMascota;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUs;
    // End of variables declaration//GEN-END:variables
}
